Agent:
  name: MyAgent
  workspace_dir:
  resources_filename: resources.yaml
  tools_filename: tools.yaml

Resources:
  SQLite:
  - name: SynthBank
    path: data/synthbank.db
    description: # Description here will override LLM generated description
  - name: Cats
    path: data/cats.db
    description: # Description here will override LLM generated description

  ChromaDB:

  Directory:

Tools:
  - module: neosophia.db.sqlite_utils
    functions: # If no functions are listed, all from the module will be loaded
      - execute_query
      - get_table_schema
      - get_tables_from_db
  - module: neosophia.agents.tools
    functions:
      - dataframe_intersection
